/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author HP
 */
import javax.swing.JOptionPane;//used to show popup dialog boxes in swing
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bttndeliveries = new javax.swing.JButton();
        bttnadashboard = new javax.swing.JButton();
        bttnassigndeliveries = new javax.swing.JButton();
        bttnriders = new javax.swing.JButton();
        bttnprofile = new javax.swing.JButton();
        bttnlogout = new javax.swing.JButton();
        lblrider = new javax.swing.JLabel();
        lblridersname = new javax.swing.JLabel();
        lblpfp = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trecentdeliveries = new javax.swing.JTable();
        lblad = new javax.swing.JLabel();
        pcompleted = new javax.swing.JPanel();
        lblcompleted = new javax.swing.JLabel();
        lblcompletedcount = new javax.swing.JLabel();
        pactiveriders = new javax.swing.JPanel();
        lblactiveriders = new javax.swing.JLabel();
        lblactiveriderscount = new javax.swing.JLabel();
        ptotaldeliveries = new javax.swing.JPanel();
        lbltotaldeliveries = new javax.swing.JLabel();
        lbltotaldeliveriescount = new javax.swing.JLabel();
        lblrecentdeliveries1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        bttndeliveries.setBackground(new java.awt.Color(48, 48, 48));
        bttndeliveries.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttndeliveries.setForeground(new java.awt.Color(255, 255, 255));
        bttndeliveries.setText("Deliveries");
        jPanel2.add(bttndeliveries);
        bttndeliveries.setBounds(20, 210, 130, 23);

        bttnadashboard.setBackground(new java.awt.Color(48, 48, 48));
        bttnadashboard.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnadashboard.setForeground(new java.awt.Color(255, 255, 255));
        bttnadashboard.setText("Dashboard");
        bttnadashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnadashboardActionPerformed(evt);
            }
        });
        jPanel2.add(bttnadashboard);
        bttnadashboard.setBounds(20, 130, 130, 23);

        bttnassigndeliveries.setBackground(new java.awt.Color(48, 48, 48));
        bttnassigndeliveries.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnassigndeliveries.setForeground(new java.awt.Color(255, 255, 255));
        bttnassigndeliveries.setText("Assign Delivery");
        bttnassigndeliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnassigndeliveriesActionPerformed(evt);
            }
        });
        jPanel2.add(bttnassigndeliveries);
        bttnassigndeliveries.setBounds(20, 170, 130, 23);

        bttnriders.setBackground(new java.awt.Color(48, 48, 48));
        bttnriders.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnriders.setForeground(new java.awt.Color(255, 255, 255));
        bttnriders.setText("Riders");
        bttnriders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnridersActionPerformed(evt);
            }
        });
        jPanel2.add(bttnriders);
        bttnriders.setBounds(20, 250, 130, 23);

        bttnprofile.setBackground(new java.awt.Color(48, 48, 48));
        bttnprofile.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnprofile.setForeground(new java.awt.Color(255, 255, 255));
        bttnprofile.setText("Profile");
        jPanel2.add(bttnprofile);
        bttnprofile.setBounds(20, 290, 130, 23);

        bttnlogout.setBackground(new java.awt.Color(48, 48, 48));
        bttnlogout.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnlogout.setForeground(new java.awt.Color(255, 255, 255));
        bttnlogout.setText("logout");
        bttnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnlogoutActionPerformed(evt);
            }
        });
        jPanel2.add(bttnlogout);
        bttnlogout.setBounds(20, 330, 130, 23);

        lblrider.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        lblrider.setText("Admin");
        jPanel2.add(lblrider);
        lblrider.setBounds(70, 100, 37, 17);

        lblridersname.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lblridersname.setText("Admin's Name");
        jPanel2.add(lblridersname);
        lblridersname.setBounds(50, 80, 80, 17);

        lblpfp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nopfp_icon.png"))); // NOI18N
        lblpfp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblpfp);
        lblpfp.setBounds(60, 30, 54, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 180, 410);

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(null);

        trecentdeliveries.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        trecentdeliveries.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        trecentdeliveries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Delivery ID", "Calendar", "Address", "Status"
            }
        ));
        jScrollPane1.setViewportView(trecentdeliveries);

        jPanel10.add(jScrollPane1);
        jScrollPane1.setBounds(20, 240, 401, 110);

        lblad.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblad.setText("ADMIN DASHBOARD");
        jPanel10.add(lblad);
        lblad.setBounds(30, 70, 160, 20);

        pcompleted.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 48, 48), 2, true));
        pcompleted.setLayout(null);

        lblcompleted.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblcompleted.setText("Completed");
        pcompleted.add(lblcompleted);
        lblcompleted.setBounds(20, 70, 80, 16);

        lblcompletedcount.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblcompletedcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcompletedcount.setText("3");
        pcompleted.add(lblcompletedcount);
        lblcompletedcount.setBounds(57, 18, 37, 45);

        jPanel10.add(pcompleted);
        pcompleted.setBounds(310, 100, 100, 100);

        pactiveriders.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 48, 48), 2, true));
        pactiveriders.setLayout(null);

        lblactiveriders.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblactiveriders.setText("Active Riders");
        pactiveriders.add(lblactiveriders);
        lblactiveriders.setBounds(10, 70, 90, 16);

        lblactiveriderscount.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblactiveriderscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblactiveriderscount.setText("3");
        pactiveriders.add(lblactiveriderscount);
        lblactiveriderscount.setBounds(57, 18, 37, 45);

        jPanel10.add(pactiveriders);
        pactiveriders.setBounds(180, 100, 100, 100);

        ptotaldeliveries.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 48, 48), 2, true));
        ptotaldeliveries.setLayout(null);

        lbltotaldeliveries.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lbltotaldeliveries.setText("Total Deliveries");
        ptotaldeliveries.add(lbltotaldeliveries);
        lbltotaldeliveries.setBounds(0, 70, 90, 14);

        lbltotaldeliveriescount.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lbltotaldeliveriescount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotaldeliveriescount.setText("3");
        ptotaldeliveries.add(lbltotaldeliveriescount);
        lbltotaldeliveriescount.setBounds(57, 18, 37, 45);

        jPanel10.add(ptotaldeliveries);
        ptotaldeliveries.setBounds(30, 100, 100, 100);

        lblrecentdeliveries1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblrecentdeliveries1.setText("RECENT DELIVERIES");
        jPanel10.add(lblrecentdeliveries1);
        lblrecentdeliveries1.setBounds(30, 220, 120, 14);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(180, 0, 440, 410);

        setBounds(0, 0, 633, 418);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnadashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnadashboardActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bttnadashboardActionPerformed

    private void bttnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnlogoutActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Logout",
        JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {

        Login lg = new Login();
        lg.setVisible(true);

        this.dispose(); // closes current dashboard
    }
    }//GEN-LAST:event_bttnlogoutActionPerformed

    private void bttnassigndeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnassigndeliveriesActionPerformed
        // TODO add your handling code here:
        AssignDelivery assign = new AssignDelivery();
        
        assign.setVisible(true);
        
        this.dispose();

    }//GEN-LAST:event_bttnassigndeliveriesActionPerformed

    private void bttnridersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnridersActionPerformed
        // TODO add your handling code here:
        RidersList rider = new RidersList();
        
        rider.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_bttnridersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnadashboard;
    private javax.swing.JButton bttnassigndeliveries;
    private javax.swing.JButton bttndeliveries;
    private javax.swing.JButton bttnlogout;
    private javax.swing.JButton bttnprofile;
    private javax.swing.JButton bttnriders;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblactiveriders;
    private javax.swing.JLabel lblactiveriderscount;
    private javax.swing.JLabel lblad;
    private javax.swing.JLabel lblcompleted;
    private javax.swing.JLabel lblcompletedcount;
    private javax.swing.JLabel lblpfp;
    private javax.swing.JLabel lblrecentdeliveries1;
    private javax.swing.JLabel lblrider;
    private javax.swing.JLabel lblridersname;
    private javax.swing.JLabel lbltotaldeliveries;
    private javax.swing.JLabel lbltotaldeliveriescount;
    private javax.swing.JPanel pactiveriders;
    private javax.swing.JPanel pcompleted;
    private javax.swing.JPanel ptotaldeliveries;
    private javax.swing.JTable trecentdeliveries;
    // End of variables declaration//GEN-END:variables
}
