/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author HP
 */
public class AssignDelivery extends javax.swing.JFrame {
    

    /**
     * Creates new form AssignDelivery
     */
    public AssignDelivery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldeliverydetails = new javax.swing.JLabel();
        lblcustomer = new javax.swing.JLabel();
        lbladd = new javax.swing.JLabel();
        lblselectrider = new javax.swing.JLabel();
        lblchooserider = new javax.swing.JLabel();
        cbrider = new javax.swing.JComboBox<>();
        lblnotes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taanotes = new javax.swing.JTextArea();
        bttnupdatestatus1 = new javax.swing.JButton();
        bttnus = new javax.swing.JButton();
        lblcustomer1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(210, 180, 140));
        jPanel1.setLayout(null);

        lbldeliverydetails.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbldeliverydetails.setForeground(new java.awt.Color(62, 39, 35));
        lbldeliverydetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldeliverydetails.setText("DELIVERY DETAILS");
        jPanel1.add(lbldeliverydetails);
        lbldeliverydetails.setBounds(20, 30, 190, 20);

        lblcustomer.setForeground(new java.awt.Color(62, 39, 35));
        lblcustomer.setText("Delivery ID:");
        jPanel1.add(lblcustomer);
        lblcustomer.setBounds(30, 60, 100, 16);

        lbladd.setForeground(new java.awt.Color(62, 39, 35));
        lbladd.setText("Address:");
        jPanel1.add(lbladd);
        lbladd.setBounds(30, 100, 50, 16);

        lblselectrider.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblselectrider.setForeground(new java.awt.Color(62, 39, 35));
        lblselectrider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblselectrider.setText("SELECT RIDER");
        jPanel1.add(lblselectrider);
        lblselectrider.setBounds(20, 230, 110, 16);

        lblchooserider.setForeground(new java.awt.Color(62, 39, 35));
        lblchooserider.setText("Choose Rider:");
        jPanel1.add(lblchooserider);
        lblchooserider.setBounds(40, 250, 100, 30);

        cbrider.setBackground(new java.awt.Color(111, 78, 55));
        cbrider.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cbrider.setForeground(new java.awt.Color(62, 39, 35));
        cbrider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kim", "Sam", "Janah" }));
        cbrider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbriderActionPerformed(evt);
            }
        });
        jPanel1.add(cbrider);
        cbrider.setBounds(130, 250, 150, 30);

        lblnotes.setForeground(new java.awt.Color(62, 39, 35));
        lblnotes.setText("Notes (Optional):");
        jPanel1.add(lblnotes);
        lblnotes.setBounds(30, 130, 100, 16);

        taanotes.setColumns(20);
        taanotes.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        taanotes.setRows(5);
        jScrollPane1.setViewportView(taanotes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 150, 280, 70);

        bttnupdatestatus1.setBackground(new java.awt.Color(111, 78, 55));
        bttnupdatestatus1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bttnupdatestatus1.setForeground(new java.awt.Color(243, 233, 220));
        bttnupdatestatus1.setText("ASSIGN DELIVERY");
        bttnupdatestatus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnupdatestatus1ActionPerformed(evt);
            }
        });
        jPanel1.add(bttnupdatestatus1);
        bttnupdatestatus1.setBounds(40, 300, 260, 23);

        bttnus.setBackground(new java.awt.Color(111, 78, 55));
        bttnus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bttnus.setForeground(new java.awt.Color(243, 233, 220));
        bttnus.setText("BACK TO DASHBOARD");
        bttnus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnusActionPerformed(evt);
            }
        });
        jPanel1.add(bttnus);
        bttnus.setBounds(40, 330, 260, 23);

        lblcustomer1.setForeground(new java.awt.Color(62, 39, 35));
        lblcustomer1.setText("Customer Name:");
        jPanel1.add(lblcustomer1);
        lblcustomer1.setBounds(30, 80, 100, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 340, 390);

        setBounds(0, 0, 355, 395);
    }// </editor-fold>//GEN-END:initComponents

    private void cbriderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbriderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbriderActionPerformed

    private void bttnupdatestatus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnupdatestatus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnupdatestatus1ActionPerformed

    private void bttnusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AssignDelivery().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnupdatestatus1;
    private javax.swing.JButton bttnus;
    private javax.swing.JComboBox<String> cbrider;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbladd;
    private javax.swing.JLabel lblchooserider;
    private javax.swing.JLabel lblcustomer;
    private javax.swing.JLabel lblcustomer1;
    private javax.swing.JLabel lbldeliverydetails;
    private javax.swing.JLabel lblnotes;
    private javax.swing.JLabel lblselectrider;
    private javax.swing.JTextArea taanotes;
    // End of variables declaration//GEN-END:variables
}
