/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author HP
 */
public class AssignDelivery extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AssignDelivery.class.getName());

    /**
     * Creates new form AssignDelivery
     */
    public AssignDelivery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldeliverydetails = new javax.swing.JLabel();
        lblcustomer = new javax.swing.JLabel();
        lbladd = new javax.swing.JLabel();
        lblselectrider = new javax.swing.JLabel();
        lblchooserider = new javax.swing.JLabel();
        cbrider = new javax.swing.JComboBox<>();
        lblnotes = new javax.swing.JLabel();
        bttnupdatestatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taanotes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lbldeliverydetails.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbldeliverydetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldeliverydetails.setText("DELIVERY DETAILS");
        jPanel1.add(lbldeliverydetails);
        lbldeliverydetails.setBounds(10, 20, 150, 20);

        lblcustomer.setText("Customer Name:");
        jPanel1.add(lblcustomer);
        lblcustomer.setBounds(30, 50, 100, 16);

        lbladd.setText("Address:");
        jPanel1.add(lbladd);
        lbladd.setBounds(30, 80, 50, 16);

        lblselectrider.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblselectrider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblselectrider.setText("SELECT RIDER");
        jPanel1.add(lblselectrider);
        lblselectrider.setBounds(20, 210, 110, 16);

        lblchooserider.setText("Choose Rider:");
        jPanel1.add(lblchooserider);
        lblchooserider.setBounds(40, 240, 100, 30);

        cbrider.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        cbrider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rider 1", "Rider 2", "Rider 3" }));
        jPanel1.add(cbrider);
        cbrider.setBounds(130, 240, 150, 30);

        lblnotes.setText("Notes (Optional):");
        jPanel1.add(lblnotes);
        lblnotes.setBounds(30, 110, 100, 16);

        bttnupdatestatus.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnupdatestatus.setText("UPDATE STATUS");
        jPanel1.add(bttnupdatestatus);
        bttnupdatestatus.setBounds(70, 300, 210, 23);

        taanotes.setColumns(20);
        taanotes.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        taanotes.setRows(5);
        jScrollPane1.setViewportView(taanotes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 280, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 340, 370);

        setBounds(0, 0, 355, 375);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AssignDelivery().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnupdatestatus;
    private javax.swing.JComboBox<String> cbrider;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbladd;
    private javax.swing.JLabel lblchooserider;
    private javax.swing.JLabel lblcustomer;
    private javax.swing.JLabel lbldeliverydetails;
    private javax.swing.JLabel lblnotes;
    private javax.swing.JLabel lblselectrider;
    private javax.swing.JTextArea taanotes;
    // End of variables declaration//GEN-END:variables
}
