/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author HP
 */
import javax.swing.JOptionPane;//used to show popup dialog boxes in swing
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginform = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        pspass = new javax.swing.JPasswordField();
        lblusername = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        cbrole = new javax.swing.JComboBox<>();
        bttnlogin = new javax.swing.JButton();
        lblcontactadmin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginform.setBackground(new java.awt.Color(220, 220, 220));
        loginform.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAFE, ANO TARA?");
        loginform.add(jLabel1);
        jLabel1.setBounds(30, 80, 240, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DELIVERY MONITORING SYSTEM");
        loginform.add(jLabel2);
        jLabel2.setBounds(50, 110, 190, 14);

        tfusername.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });
        loginform.add(tfusername);
        tfusername.setBounds(90, 180, 180, 30);

        pspass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pspassActionPerformed(evt);
            }
        });
        loginform.add(pspass);
        pspass.setBounds(90, 220, 180, 30);

        lblusername.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusername.setText("Username:");
        loginform.add(lblusername);
        lblusername.setBounds(20, 190, 70, 19);

        lblpass.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpass.setText("Password:");
        loginform.add(lblpass);
        lblpass.setBounds(20, 220, 70, 19);

        cbrole.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        cbrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rider", "Admin" }));
        cbrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbroleActionPerformed(evt);
            }
        });
        loginform.add(cbrole);
        cbrole.setBounds(50, 270, 210, 30);

        bttnlogin.setBackground(new java.awt.Color(48, 48, 48));
        bttnlogin.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        bttnlogin.setForeground(new java.awt.Color(255, 255, 255));
        bttnlogin.setText("LOGIN");
        bttnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnloginActionPerformed(evt);
            }
        });
        loginform.add(bttnlogin);
        bttnlogin.setBounds(110, 320, 72, 24);

        lblcontactadmin.setText("<html><u>No account? Contact Admin</u></html>");
        loginform.add(lblcontactadmin);
        lblcontactadmin.setBounds(80, 380, 151, 16);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coffee_icon.png"))); // NOI18N
        loginform.add(jLabel8);
        jLabel8.setBounds(90, 10, 110, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginform, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginform, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 315, 446);
    }// </editor-fold>//GEN-END:initComponents

    private void pspassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pspassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pspassActionPerformed

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusernameActionPerformed

    private void cbroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbroleActionPerformed

    private void bttnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnloginActionPerformed
        // TODO add your handling code here:                                           
    String username = tfusername.getText();
    String password = String.valueOf(pspass.getPassword());
    String role = cbrole.getSelectedItem().toString();

    // rider login
    if(role.equals("Rider")){

        if(
            (username.equals("Kim") && password.equals("111")) || //or
            (username.equals("Sam") && password.equals("222")) ||
            (username.equals("Ja") && password.equals("333"))
        ){

            JOptionPane.showMessageDialog(this, "Welcome Rider!");

            RiderDashboard rd = new RiderDashboard();
            rd.setVisible(true);

            this.dispose();

        }else{

            JOptionPane.showMessageDialog(
                this,
                "Invalid username or password"
            );
        }
    }

    // admin login
    else if(role.equals("Admin")){

        if(username.equals("ksj") && password.equals("060606")){

            JOptionPane.showMessageDialog(this, "Welcome Admin!");

            AdminDashboard ad = new AdminDashboard();
            ad.setVisible(true);

            this.dispose();

        }else{

            JOptionPane.showMessageDialog(
                this,
                "Invalid username or password"
            );
        }
    }
    }//GEN-LAST:event_bttnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnlogin;
    private javax.swing.JComboBox<String> cbrole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblcontactadmin;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPanel loginform;
    private javax.swing.JPasswordField pspass;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
