/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author HP
 */
public class RidersList extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RidersList.class.getName());

    /**
     * Creates new form RidersList
     */
    public RidersList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablerstatus = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bttnus = new javax.swing.JButton();
        bttnaddr = new javax.swing.JButton();
        bttndelr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(210, 180, 140));
        jPanel1.setLayout(null);

        tablerstatus.setForeground(new java.awt.Color(62, 39, 35));
        tablerstatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rider ID", "Rider Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablerstatus);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 350, 200);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 39, 35));
        jLabel1.setText("RIDERS STATUS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 150, 24);

        bttnus.setBackground(new java.awt.Color(111, 78, 55));
        bttnus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bttnus.setForeground(new java.awt.Color(243, 233, 220));
        bttnus.setText("BACK TO DASHBOARD");
        bttnus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnusActionPerformed(evt);
            }
        });
        jPanel1.add(bttnus);
        bttnus.setBounds(50, 300, 280, 23);

        bttnaddr.setBackground(new java.awt.Color(111, 78, 55));
        bttnaddr.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bttnaddr.setForeground(new java.awt.Color(243, 233, 220));
        bttnaddr.setText("ADD RIDER");
        bttnaddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnaddrActionPerformed(evt);
            }
        });
        jPanel1.add(bttnaddr);
        bttnaddr.setBounds(50, 270, 120, 23);

        bttndelr.setBackground(new java.awt.Color(111, 78, 55));
        bttndelr.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bttndelr.setForeground(new java.awt.Color(243, 233, 220));
        bttndelr.setText("DELETE RIDER");
        bttndelr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttndelrActionPerformed(evt);
            }
        });
        jPanel1.add(bttndelr);
        bttndelr.setBounds(210, 270, 120, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 350);

        setBounds(0, 0, 400, 358);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnusActionPerformed

    private void bttnaddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnaddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnaddrActionPerformed

    private void bttndelrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttndelrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttndelrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RidersList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnaddr;
    private javax.swing.JButton bttndelr;
    private javax.swing.JButton bttnus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablerstatus;
    // End of variables declaration//GEN-END:variables
}
