/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author saman
 */
public class RiderProfile extends javax.swing.JFrame {

    /**
     * Creates new form RiderProfile
     */
    public RiderProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblad = new javax.swing.JLabel();
        lblad1 = new javax.swing.JLabel();
        lblad2 = new javax.swing.JLabel();
        lblad3 = new javax.swing.JLabel();
        lblad4 = new javax.swing.JLabel();
        lblpfp = new javax.swing.JLabel();
        bttnus = new javax.swing.JButton();
        bttnus1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));

        lblad.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblad.setForeground(new java.awt.Color(62, 39, 35));
        lblad.setText("ADMIN PROFILE");

        lblad1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblad1.setForeground(new java.awt.Color(62, 39, 35));
        lblad1.setText("RIDER'S ID:");

        lblad2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblad2.setForeground(new java.awt.Color(62, 39, 35));
        lblad2.setText("FULL NAME:");

        lblad3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblad3.setForeground(new java.awt.Color(62, 39, 35));
        lblad3.setText("ADDRESS:");

        lblad4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblad4.setForeground(new java.awt.Color(62, 39, 35));
        lblad4.setText("CONTACT NO.:");

        lblpfp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile3.png"))); // NOI18N
        lblpfp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bttnus.setBackground(new java.awt.Color(111, 78, 55));
        bttnus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bttnus.setForeground(new java.awt.Color(243, 233, 220));
        bttnus.setText("BACK TO DASHBOARD");
        bttnus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnusActionPerformed(evt);
            }
        });

        bttnus1.setBackground(new java.awt.Color(111, 78, 55));
        bttnus1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bttnus1.setForeground(new java.awt.Color(243, 233, 220));
        bttnus1.setText("LOG OUT");
        bttnus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnus1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblpfp)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblad1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblad2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblad3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblad4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttnus1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttnus, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblpfp)
                .addGap(18, 18, 18)
                .addComponent(lblad1)
                .addGap(9, 9, 9)
                .addComponent(lblad2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblad3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblad4)
                .addGap(75, 75, 75)
                .addComponent(bttnus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnus1)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 270, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnusActionPerformed

    private void bttnus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnus1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiderProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiderProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiderProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiderProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiderProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnus;
    private javax.swing.JButton bttnus1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblad;
    private javax.swing.JLabel lblad1;
    private javax.swing.JLabel lblad2;
    private javax.swing.JLabel lblad3;
    private javax.swing.JLabel lblad4;
    private javax.swing.JLabel lblpfp;
    // End of variables declaration//GEN-END:variables
}
