/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author HP
 */
import javax.swing.JOptionPane; //used to show popup dialog boxes in swing
public class RiderDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RiderDashboard.class.getName());

    /**
     * Creates new form RiderDashboard
     */
    public RiderDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bttnupdatestatus = new javax.swing.JButton();
        bttnrdashboard = new javax.swing.JButton();
        bttnmydeliveries = new javax.swing.JButton();
        bttnhistory = new javax.swing.JButton();
        bttnprofile = new javax.swing.JButton();
        bttnlogout = new javax.swing.JButton();
        lblrider = new javax.swing.JLabel();
        lblridername = new javax.swing.JLabel();
        lblpfp = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tassigneddeliveries = new javax.swing.JTable();
        lblriderdashboard = new javax.swing.JLabel();
        ppending = new javax.swing.JPanel();
        lblpending = new javax.swing.JLabel();
        lblpendingcount1 = new javax.swing.JLabel();
        pout = new javax.swing.JPanel();
        lbloutcount1 = new javax.swing.JLabel();
        lblout1 = new javax.swing.JLabel();
        pcompleted = new javax.swing.JPanel();
        lblcompletedcount = new javax.swing.JLabel();
        lblout = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ppendingrcount = new javax.swing.JPanel();
        lblpendingr = new javax.swing.JLabel();
        lblpendingrcount = new javax.swing.JLabel();
        poutfordelivery = new javax.swing.JPanel();
        lbloutfordelivery = new javax.swing.JLabel();
        lbloutfordeliverycount = new javax.swing.JLabel();
        prcompleted = new javax.swing.JPanel();
        lblrcompleted = new javax.swing.JLabel();
        lblcompletedrcount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        bttnupdatestatus.setBackground(new java.awt.Color(48, 48, 48));
        bttnupdatestatus.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnupdatestatus.setForeground(new java.awt.Color(255, 255, 255));
        bttnupdatestatus.setText("Update Status");
        bttnupdatestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnupdatestatusActionPerformed(evt);
            }
        });
        jPanel2.add(bttnupdatestatus);
        bttnupdatestatus.setBounds(30, 210, 130, 23);

        bttnrdashboard.setBackground(new java.awt.Color(48, 48, 48));
        bttnrdashboard.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnrdashboard.setForeground(new java.awt.Color(255, 255, 255));
        bttnrdashboard.setText("Dashboard");
        bttnrdashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnrdashboardActionPerformed(evt);
            }
        });
        jPanel2.add(bttnrdashboard);
        bttnrdashboard.setBounds(30, 130, 130, 23);

        bttnmydeliveries.setBackground(new java.awt.Color(48, 48, 48));
        bttnmydeliveries.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnmydeliveries.setForeground(new java.awt.Color(255, 255, 255));
        bttnmydeliveries.setText("My Deliveries");
        jPanel2.add(bttnmydeliveries);
        bttnmydeliveries.setBounds(30, 170, 130, 23);

        bttnhistory.setBackground(new java.awt.Color(48, 48, 48));
        bttnhistory.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnhistory.setForeground(new java.awt.Color(255, 255, 255));
        bttnhistory.setText("History");
        jPanel2.add(bttnhistory);
        bttnhistory.setBounds(30, 250, 130, 23);

        bttnprofile.setBackground(new java.awt.Color(48, 48, 48));
        bttnprofile.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnprofile.setForeground(new java.awt.Color(255, 255, 255));
        bttnprofile.setText("Profile");
        jPanel2.add(bttnprofile);
        bttnprofile.setBounds(30, 290, 130, 23);

        bttnlogout.setBackground(new java.awt.Color(48, 48, 48));
        bttnlogout.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bttnlogout.setForeground(new java.awt.Color(255, 255, 255));
        bttnlogout.setText("logout");
        bttnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnlogoutActionPerformed(evt);
            }
        });
        jPanel2.add(bttnlogout);
        bttnlogout.setBounds(30, 330, 130, 23);

        lblrider.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        lblrider.setText("Rider");
        jPanel2.add(lblrider);
        lblrider.setBounds(70, 100, 37, 17);

        lblridername.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lblridername.setText("Rider's Name");
        jPanel2.add(lblridername);
        lblridername.setBounds(50, 80, 80, 17);

        lblpfp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nopfp_icon.png"))); // NOI18N
        lblpfp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblpfp);
        lblpfp.setBounds(60, 30, 54, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 180, 420);

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(null);

        tassigneddeliveries.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tassigneddeliveries.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        tassigneddeliveries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Delivery ID", "Calendar", "Address", "Status"
            }
        ));
        jScrollPane1.setViewportView(tassigneddeliveries);

        jPanel10.add(jScrollPane1);
        jScrollPane1.setBounds(20, 240, 401, 110);

        lblriderdashboard.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblriderdashboard.setText("RIDER DASHBOARD");
        jPanel10.add(lblriderdashboard);
        lblriderdashboard.setBounds(20, 50, 160, 20);

        ppending.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 48, 48), 2, true));
        ppending.setLayout(null);

        lblpending.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblpending.setText("Pending");
        ppending.add(lblpending);
        lblpending.setBounds(38, 67, 54, 16);

        lblpendingcount1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblpendingcount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpendingcount1.setText("3");
        ppending.add(lblpendingcount1);
        lblpendingcount1.setBounds(57, 18, 37, 45);

        jPanel10.add(ppending);
        ppending.setBounds(20, 80, 0, 0);

        pout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 48, 48), 2, true));
        pout.setLayout(null);

        lbloutcount1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lbloutcount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbloutcount1.setText("3");
        pout.add(lbloutcount1);
        lbloutcount1.setBounds(55, 20, 37, 45);

        lblout1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblout1.setText("Out");
        pout.add(lblout1);
        lblout1.setBounds(60, 70, 30, 16);

        jPanel10.add(pout);
        pout.setBounds(170, 80, 0, 0);

        pcompleted.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 48, 48), 2, true));
        pcompleted.setLayout(null);

        lblcompletedcount.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblcompletedcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcompletedcount.setText("3");
        pcompleted.add(lblcompletedcount);
        lblcompletedcount.setBounds(55, 20, 37, 45);

        lblout.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblout.setText("Completed");
        pcompleted.add(lblout);
        lblout.setBounds(20, 70, 90, 16);

        jPanel10.add(pcompleted);
        pcompleted.setBounds(310, 80, 0, 0);

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel4.setText("MY ASSIGNED DELIVERIES");
        jPanel10.add(jLabel4);
        jLabel4.setBounds(20, 210, 160, 14);

        ppendingrcount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 48, 48), 2, true));
        ppendingrcount.setLayout(null);

        lblpendingr.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblpendingr.setText("Pending");
        ppendingrcount.add(lblpendingr);
        lblpendingr.setBounds(40, 70, 50, 14);

        lblpendingrcount.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblpendingrcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpendingrcount.setText("3");
        ppendingrcount.add(lblpendingrcount);
        lblpendingrcount.setBounds(57, 18, 37, 45);

        jPanel10.add(ppendingrcount);
        ppendingrcount.setBounds(20, 80, 100, 100);

        poutfordelivery.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 48, 48), 2, true));
        poutfordelivery.setLayout(null);

        lbloutfordelivery.setFont(new java.awt.Font("Segoe UI Emoji", 1, 10)); // NOI18N
        lbloutfordelivery.setText("Out for Delivery");
        poutfordelivery.add(lbloutfordelivery);
        lbloutfordelivery.setBounds(20, 70, 100, 14);

        lbloutfordeliverycount.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lbloutfordeliverycount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbloutfordeliverycount.setText("3");
        poutfordelivery.add(lbloutfordeliverycount);
        lbloutfordeliverycount.setBounds(57, 18, 37, 45);

        jPanel10.add(poutfordelivery);
        poutfordelivery.setBounds(150, 80, 100, 100);

        prcompleted.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 48, 48), 2, true));
        prcompleted.setLayout(null);

        lblrcompleted.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblrcompleted.setText("Completed");
        prcompleted.add(lblrcompleted);
        lblrcompleted.setBounds(30, 70, 70, 14);

        lblcompletedrcount.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblcompletedrcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcompletedrcount.setText("3");
        prcompleted.add(lblcompletedrcount);
        lblcompletedrcount.setBounds(57, 18, 37, 45);

        jPanel10.add(prcompleted);
        prcompleted.setBounds(290, 80, 100, 100);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(180, 0, 430, 420);

        setBounds(0, 0, 627, 427);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnrdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnrdashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnrdashboardActionPerformed

    private void bttnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnlogoutActionPerformed
        // TODO add your handling code here:
    int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Logout",
        JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {

        Login lg = new Login();
        lg.setVisible(true);

        this.dispose(); // closes current dashboard
    }
    }//GEN-LAST:event_bttnlogoutActionPerformed

    private void bttnupdatestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnupdatestatusActionPerformed
        // TODO add your handling code here:
    UpdateStatus update = new UpdateStatus();

    update.setVisible(true);

    this.dispose();

    }//GEN-LAST:event_bttnupdatestatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RiderDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnhistory;
    private javax.swing.JButton bttnlogout;
    private javax.swing.JButton bttnmydeliveries;
    private javax.swing.JButton bttnprofile;
    private javax.swing.JButton bttnrdashboard;
    private javax.swing.JButton bttnupdatestatus;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcompletedcount;
    private javax.swing.JLabel lblcompletedrcount;
    private javax.swing.JLabel lblout;
    private javax.swing.JLabel lblout1;
    private javax.swing.JLabel lbloutcount1;
    private javax.swing.JLabel lbloutfordelivery;
    private javax.swing.JLabel lbloutfordeliverycount;
    private javax.swing.JLabel lblpending;
    private javax.swing.JLabel lblpendingcount1;
    private javax.swing.JLabel lblpendingr;
    private javax.swing.JLabel lblpendingrcount;
    private javax.swing.JLabel lblpfp;
    private javax.swing.JLabel lblrcompleted;
    private javax.swing.JLabel lblrider;
    private javax.swing.JLabel lblriderdashboard;
    private javax.swing.JLabel lblridername;
    private javax.swing.JPanel pcompleted;
    private javax.swing.JPanel pout;
    private javax.swing.JPanel poutfordelivery;
    private javax.swing.JPanel ppending;
    private javax.swing.JPanel ppendingrcount;
    private javax.swing.JPanel prcompleted;
    private javax.swing.JTable tassigneddeliveries;
    // End of variables declaration//GEN-END:variables
}
