/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author HP
 */
public class UpdateStatus extends javax.swing.JFrame {
    

    /**
     * Creates new form UpdateStatus
     */
    public UpdateStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeliveryStatusBoard = new javax.swing.JPanel();
        lblDeliveryDetails = new javax.swing.JLabel();
        lblDeliveryID = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCurrentStatus = new javax.swing.JLabel();
        UpdateStatus = new javax.swing.JLabel();
        lblSelectNewStat = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        lblusnotes = new javax.swing.JLabel();
        btnUpdateStatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_Notes = new javax.swing.JTextArea();
        btnBacktoDashboard = new javax.swing.JButton();
        txtCurrentStatus = new javax.swing.JTextField();
        txtDeliveryId = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        DeliveryStatusBoard.setBackground(new java.awt.Color(210, 180, 140));
        DeliveryStatusBoard.setLayout(null);

        lblDeliveryDetails.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblDeliveryDetails.setForeground(new java.awt.Color(62, 39, 35));
        lblDeliveryDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeliveryDetails.setText("DELIVERY DETAILS");
        DeliveryStatusBoard.add(lblDeliveryDetails);
        lblDeliveryDetails.setBounds(20, 20, 190, 20);

        lblDeliveryID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblDeliveryID.setForeground(new java.awt.Color(62, 39, 35));
        lblDeliveryID.setText("Delivery ID:");
        DeliveryStatusBoard.add(lblDeliveryID);
        lblDeliveryID.setBounds(30, 50, 70, 16);

        lblCustomer.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(62, 39, 35));
        lblCustomer.setText("Customer:");
        DeliveryStatusBoard.add(lblCustomer);
        lblCustomer.setBounds(30, 70, 60, 16);

        lblAddress.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(62, 39, 35));
        lblAddress.setText("Address:");
        DeliveryStatusBoard.add(lblAddress);
        lblAddress.setBounds(30, 90, 50, 16);

        lblCurrentStatus.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblCurrentStatus.setForeground(new java.awt.Color(62, 39, 35));
        lblCurrentStatus.setText("Current Status:");
        DeliveryStatusBoard.add(lblCurrentStatus);
        lblCurrentStatus.setBounds(30, 110, 90, 16);

        UpdateStatus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        UpdateStatus.setForeground(new java.awt.Color(62, 39, 35));
        UpdateStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpdateStatus.setText("UPDATE STATUS");
        DeliveryStatusBoard.add(UpdateStatus);
        UpdateStatus.setBounds(20, 140, 140, 19);

        lblSelectNewStat.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblSelectNewStat.setForeground(new java.awt.Color(62, 39, 35));
        lblSelectNewStat.setText("Select New Status:");
        DeliveryStatusBoard.add(lblSelectNewStat);
        lblSelectNewStat.setBounds(30, 170, 100, 16);

        cmbStatus.setBackground(new java.awt.Color(111, 78, 55));
        cmbStatus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cmbStatus.setForeground(new java.awt.Color(62, 39, 35));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Picked Up", "Out for Delivery", "Delivered" }));
        DeliveryStatusBoard.add(cmbStatus);
        cmbStatus.setBounds(150, 170, 150, 22);

        lblusnotes.setBackground(new java.awt.Color(243, 233, 220));
        lblusnotes.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblusnotes.setForeground(new java.awt.Color(62, 39, 35));
        lblusnotes.setText("Notes (Optional):");
        DeliveryStatusBoard.add(lblusnotes);
        lblusnotes.setBounds(40, 200, 110, 16);

        btnUpdateStatus.setBackground(new java.awt.Color(111, 78, 55));
        btnUpdateStatus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(243, 233, 220));
        btnUpdateStatus.setText("UPDATE STATUS");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });
        DeliveryStatusBoard.add(btnUpdateStatus);
        btnUpdateStatus.setBounds(50, 300, 260, 23);

        textArea_Notes.setColumns(20);
        textArea_Notes.setRows(5);
        jScrollPane1.setViewportView(textArea_Notes);

        DeliveryStatusBoard.add(jScrollPane1);
        jScrollPane1.setBounds(30, 220, 300, 70);

        btnBacktoDashboard.setBackground(new java.awt.Color(111, 78, 55));
        btnBacktoDashboard.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBacktoDashboard.setForeground(new java.awt.Color(243, 233, 220));
        btnBacktoDashboard.setText("BACK TO DASHBOARD");
        btnBacktoDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktoDashboardActionPerformed(evt);
            }
        });
        DeliveryStatusBoard.add(btnBacktoDashboard);
        btnBacktoDashboard.setBounds(50, 330, 260, 23);
        DeliveryStatusBoard.add(txtCurrentStatus);
        txtCurrentStatus.setBounds(150, 110, 180, 22);

        txtDeliveryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeliveryIdActionPerformed(evt);
            }
        });
        DeliveryStatusBoard.add(txtDeliveryId);
        txtDeliveryId.setBounds(150, 50, 180, 22);

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        DeliveryStatusBoard.add(txtCustomerName);
        txtCustomerName.setBounds(150, 70, 180, 22);
        DeliveryStatusBoard.add(txtAddress);
        txtAddress.setBounds(150, 90, 180, 22);

        getContentPane().add(DeliveryStatusBoard);
        DeliveryStatusBoard.setBounds(0, 0, 360, 370);

        setBounds(0, 0, 375, 370);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnBacktoDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktoDashboardActionPerformed
       new RiderDashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBacktoDashboardActionPerformed

    private void txtDeliveryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeliveryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeliveryIdActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateStatus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DeliveryStatusBoard;
    private javax.swing.JLabel UpdateStatus;
    private javax.swing.JButton btnBacktoDashboard;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCurrentStatus;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDeliveryDetails;
    private javax.swing.JLabel lblDeliveryID;
    private javax.swing.JLabel lblSelectNewStat;
    private javax.swing.JLabel lblusnotes;
    private javax.swing.JTextArea textArea_Notes;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCurrentStatus;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtDeliveryId;
    // End of variables declaration//GEN-END:variables
}
