/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author HP
 */
public class UpdateStatus extends javax.swing.JFrame {
    

    /**
     * Creates new form UpdateStatus
     */
    public UpdateStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldeliverydetails = new javax.swing.JLabel();
        lbldeliveryid = new javax.swing.JLabel();
        lblcustomer = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        lblcurrstatus = new javax.swing.JLabel();
        lblupdatestatus = new javax.swing.JLabel();
        lblnewstatus = new javax.swing.JLabel();
        cbstatus = new javax.swing.JComboBox<>();
        lblusnotes = new javax.swing.JLabel();
        bttnupdatestatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tausnotes = new javax.swing.JTextArea();
        bttnus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(210, 180, 140));
        jPanel1.setLayout(null);

        lbldeliverydetails.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbldeliverydetails.setForeground(new java.awt.Color(62, 39, 35));
        lbldeliverydetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldeliverydetails.setText("DELIVERY DETAILS");
        jPanel1.add(lbldeliverydetails);
        lbldeliverydetails.setBounds(20, 20, 190, 20);

        lbldeliveryid.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbldeliveryid.setForeground(new java.awt.Color(62, 39, 35));
        lbldeliveryid.setText("Delivery ID:");
        jPanel1.add(lbldeliveryid);
        lbldeliveryid.setBounds(30, 50, 70, 16);

        lblcustomer.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblcustomer.setForeground(new java.awt.Color(62, 39, 35));
        lblcustomer.setText("Customer:");
        jPanel1.add(lblcustomer);
        lblcustomer.setBounds(30, 70, 60, 16);

        lbladdress.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbladdress.setForeground(new java.awt.Color(62, 39, 35));
        lbladdress.setText("Address:");
        jPanel1.add(lbladdress);
        lbladdress.setBounds(30, 90, 50, 16);

        lblcurrstatus.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblcurrstatus.setForeground(new java.awt.Color(62, 39, 35));
        lblcurrstatus.setText("Current Status:");
        jPanel1.add(lblcurrstatus);
        lblcurrstatus.setBounds(30, 110, 90, 16);

        lblupdatestatus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblupdatestatus.setForeground(new java.awt.Color(62, 39, 35));
        lblupdatestatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblupdatestatus.setText("UPDATE STATUS");
        jPanel1.add(lblupdatestatus);
        lblupdatestatus.setBounds(20, 140, 140, 19);

        lblnewstatus.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblnewstatus.setForeground(new java.awt.Color(62, 39, 35));
        lblnewstatus.setText("Select New Status:");
        jPanel1.add(lblnewstatus);
        lblnewstatus.setBounds(30, 170, 100, 16);

        cbstatus.setBackground(new java.awt.Color(111, 78, 55));
        cbstatus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cbstatus.setForeground(new java.awt.Color(62, 39, 35));
        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Picked Up", "Out for Delivery", "Delivered" }));
        jPanel1.add(cbstatus);
        cbstatus.setBounds(150, 170, 150, 22);

        lblusnotes.setBackground(new java.awt.Color(243, 233, 220));
        lblusnotes.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblusnotes.setForeground(new java.awt.Color(62, 39, 35));
        lblusnotes.setText("Notes (Optional):");
        jPanel1.add(lblusnotes);
        lblusnotes.setBounds(40, 200, 110, 16);

        bttnupdatestatus.setBackground(new java.awt.Color(111, 78, 55));
        bttnupdatestatus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bttnupdatestatus.setForeground(new java.awt.Color(243, 233, 220));
        bttnupdatestatus.setText("UPDATE STATUS");
        bttnupdatestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnupdatestatusActionPerformed(evt);
            }
        });
        jPanel1.add(bttnupdatestatus);
        bttnupdatestatus.setBounds(50, 300, 260, 23);

        tausnotes.setColumns(20);
        tausnotes.setRows(5);
        jScrollPane1.setViewportView(tausnotes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 220, 300, 70);

        bttnus.setBackground(new java.awt.Color(111, 78, 55));
        bttnus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bttnus.setForeground(new java.awt.Color(243, 233, 220));
        bttnus.setText("BACK TO DASHBOARD");
        bttnus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnusActionPerformed(evt);
            }
        });
        jPanel1.add(bttnus);
        bttnus.setBounds(50, 330, 260, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 370);

        setBounds(0, 0, 375, 370);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnupdatestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnupdatestatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnupdatestatusActionPerformed

    private void bttnusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateStatus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnupdatestatus;
    private javax.swing.JButton bttnus;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblcurrstatus;
    private javax.swing.JLabel lblcustomer;
    private javax.swing.JLabel lbldeliverydetails;
    private javax.swing.JLabel lbldeliveryid;
    private javax.swing.JLabel lblnewstatus;
    private javax.swing.JLabel lblupdatestatus;
    private javax.swing.JLabel lblusnotes;
    private javax.swing.JTextArea tausnotes;
    // End of variables declaration//GEN-END:variables
}
